# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: 'product-management-app'

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - uses: actions/labeler@v2
    - name: Setup Github Token
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Continous Integration
      run: npm ci
    - name: Building
      run: npm run build
#    - name: define user info
#      run : git config --global user.name 'meewai'
#    - name: define user email
#      run: git config --global user.email 'nmw_ng@hotmail.com'
#    - name: git remote
#      run: git remote set-url origin https://MeeWai:${{ secrets.GITHUB_TOKEN }}@github.com/MeeWai/ReactJs-Practice-Product-Management-App
    - name: Deploying
      run: npm run deploy
